config/routes.rb
Rails.application.routes.draw do
  get 'courses/oceny'
  resources :courses
  resources :students
  resources :groups
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
  has_and_belongs_to_many :groups
  has_many :course_students
  has_many :students, through: :course_students

end

app/models/course_student.rb
class CourseStudent < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :students
  has_and_belongs_to_many :courses
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :group
  has_many :course_students
  has_many :courses, through: :course_students
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy oceny ]

  # GET /courses or /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  #Get /courses/oceny
  def oceny
    @group = Group.find(params[:gr_id])
    @oceny = @course.course_students
    @students = @group.students
    if @oceny.count > 0
    else
      @students.each do |s|
        cs = CourseStudent.new
        cs.student_id = s.id
        cs.course_id = @course.id
        cs.ocena = 0
        cs.save
      end
    end
    @oceny = @course.course_students
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_url(@course), notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_url(@course), notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:nazwa, student_ids:[])
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy ]

  # GET /groups or /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1 or /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_url, notice: "Group was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: "Group was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: "Group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:nazwa, :semestr, course_ids:[] )
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
    if params.has_key?(:id)
      @student = Student.find(params[:id])
    else
      @student = Student.new
    end

  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
    id = @student.id
    respond_to do |format|
      format.html { redirect_to students_url(id: id)  }
      format.json { head :no_content }
    end

  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to students_url, notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to students_url, notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:indeks, :imie, :nazwisko, :group_id, course_ids:[])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/courses/_course.html.erb
<div id="<%= dom_id course %>">

  <tr class="bg-light">
    <td><%= course.nazwa %></td>
    <td><%= link_to "Edycja", edit_course_path(course), class: "btn btn-primary btn-sm" %></td>
  </tr>


      <% course.groups.each do |g| %>
      <tr>
        <td>    <%= g.nazwa %></td>
        <td>
          <% g.students.each do |s| %>
            <%= s.indeks %> <%= s.imie %> <%= s.nazwisko %><br>
          <% end %>
        </td>
        <td><%= link_to "Oceny", courses_oceny_path(id: course.id, gr_id: g), class: "btn btn-primary btn-sm" %></td>
      </tr>
      <% end %>






</div>

app/views/courses/_form.html.erb
<%= form_with(model: course) do |form| %>
  <% if course.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nazwa, style: "display: block" %>
    <%= form.text_field :nazwa %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to "Show this course", @course %> |
  <%= link_to "Back to courses", courses_path %>
</div>

app/views/courses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Courses</h1>

<div id="courses">
  <table class="table">
  <% @courses.each do |course| %>
    <%= render course %>



  <% end %>
  </table>
</div>

<%= link_to "New course", new_course_path %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to "Back to courses", courses_path %>
</div>

app/views/courses/oceny.html.erb
<h1>Jestem</h1>

<%= @course.nazwa %>
<%= @group.nazwa %>

<% @oceny.each do |o| %>
  <%= o.student.imie %><%=o.student.nazwisko %>
<% end %>

app/views/courses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @course %>

<div>
  <%= link_to "Edit this course", edit_course_path(@course) %> |
  <%= link_to "Back to courses", courses_path %>

  <%= button_to "Destroy this course", @course, method: :delete %>
</div>

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <tr>
    <td><%= form.text_field :nazwa %></td>
    <td><%= form.number_field :semestr %></td>
    <td></td>
    <td></td>
    <td> <%= form.submit class: "btn btn-primary" %></td>
  </tr>
  <tr>
    <td colspan="5">

      <%= form.collection_check_boxes :course_ids, Course.all, :id, :nazwa, {}, {class: "form-check form-check-inline"}  %>
    </td>
  </tr>



<% end %>

app/views/groups/_group.html.erb
  <tr>
    <td><%= group.nazwa %></td>
    <td><%= group.semestr %></td>
    <td><% group.students.each do |s| %>
        <%= s.indeks %> <%= s.imie %> <%= s.nazwisko %><br>
      <% end %></td>
    <td><% group.courses.each do |c| %>
        <%= c.nazwa %>
      <% end %></td>
    <td></td>

  </tr>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Groups</h1>

<div id="groups">
  <table class="table">
    <thead>
    <tr>
      <td>Nazwa</td>
      <td>Semestr</td>
      <td>Studenci</td>
      <td>Przedmioty</td>
      <td></td>
    </tr>
    </thead>



  <% @groups.each do |group| %>
      <%= render group %>

  <% end %>
    <%= render "form", group: Group.new %>
  </table>
</div>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @group %>

<div>
  <%= link_to "Edit this group", edit_group_path(@group) %> |
  <%= link_to "Back to groups", groups_path %>

  <%= button_to "Destroy this group", @group, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lab</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div id='form_s'>
      <tr>
        <td><%= form.text_field :indeks %></td>
        <td><%= form.text_field :imie %></td>
        <td><%= form.text_field :nazwisko %></td>
        <td><%= form.collection_select :group_id, Group.all, :id, :nazwa,{}, {class: "form-select"} %></td>
        <td><%= form.submit "Zapisz", class: "btn btn-primary btn-sm" %> </td>
      </tr>
  </div>

<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">


  <tr>
    <td><%= student.indeks %></td>
    <td><%= student.imie %></td>
    <td><%= student.nazwisko %></td>
    <td><%= student.group.nazwa %></td>
    <td><%= link_to "Edycja", edit_student_path(student), remote: true, class: "btn btn-primary btn-sm" %> </td>
    <td><%= button_to "Usuń", student, method: :delete, class: "btn btn-secondary btn-sm" %></td>
  </tr>


</div>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/edit.js.erb
$("#form_s").html("<%= escape_javascript(render partial: 'form', locals: {student: stud}) %>");

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Students</h1>

<div id="students">
  <table class="table">
  <thead>
  <tr>
    <th>Indeks</th>
    <th>Imię</th>
    <th>Nazwisko</th>
    <th>Grupa</th>
    <th></th>
  </tr>
  </thead>

  <% @students.each do |student| %>
    <%= render student %>

  <% end %>
    <%= render "form", student: @student %>
  </table>

</div>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %>

<div>
  <%= link_to "Edit this student", edit_student_path(@student) %> |
  <%= link_to "Back to students", students_path %>

  <%= button_to "Destroy this student", @student, method: :delete %>
</div>